# -*- coding: utf-8 -*-
"""SleepWellAI- DSML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a7ECy1pdA5PyZtLg-1WqRXRvp5gAV5-l

Setup and Imports
"""

!pip install -q kaggle pandas numpy scikit-learn xgboost shap matplotlib seaborn joblib
!pip install -q sentence-transformers faiss-cpu langchain openai biopython requests
!pip install -q llama-cpp-python gradio

import os, re, json, pickle, time, random, requests
import pandas as pd  #data handling
import numpy as np    #data handling
import shap, joblib, faiss, seaborn as sns  #explanation, saving/loading objects, vector search
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sentence_transformers import SentenceTransformer  #vector search
from Bio import Entrez   #pubmed queries

sns.set_style("whitegrid")

from google.colab import drive
drive.mount('/content/drive')

""" Load and Clean Dataset

"""

CSV_PATH = "/content/drive/MyDrive/Sleep_health_and_lifestyle_dataset.csv"
df = pd.read_csv(CSV_PATH)
print("✅ Raw shape:", df.shape)
df.head(3)

# Converting BP to 2 type columns Systolic and Diastolic
def parse_bp(bp):
    try:
        if pd.isna(bp): return (np.nan, np.nan)
        p = str(bp).split('/')
        return int(p[0]), int(p[1])
    except:
        return (np.nan, np.nan)

bp_parsed = df['Blood Pressure'].apply(parse_bp) #series of tuple created (120,80)
df['Systolic'] = bp_parsed.apply(lambda x: x[0])
df['Diastolic'] = bp_parsed.apply(lambda x: x[1])
df.drop(columns=['Blood Pressure'], inplace=True)
df['Sleep Disorder'] = df['Sleep Disorder'].fillna("Healthy")  #no recorded disorder considering healthy.

"""Encode + Balance Data + Train Model"""

# Encode categoricals
cat_cols = [c for c in ['Gender', 'Occupation', 'BMI Category'] if c in df.columns]
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)  #one-hot encoding and creating new columns

# Normalize target names
df['Sleep Disorder'] = df['Sleep Disorder'].replace({'None':'Healthy','No Sleep Disorder':'Healthy'})

le = LabelEncoder()
df['Sleep Disorder'] = le.fit_transform(df['Sleep Disorder'])
print("Classes:", le.classes_)

# Balance dataset
df_majority = df[df['Sleep Disorder']==0]
df_minority = df[df['Sleep Disorder']!=0]
df_minority_up = resample(df_minority, replace=True, n_samples=len(df_majority), random_state=42)  #upsampling minority data until both classes have same size
df_balanced = pd.concat([df_majority, df_minority_up])

drop_cols = [c for c in ['Person ID', 'Sleep Disorder'] if c in df_balanced.columns]
features = df_balanced.drop(drop_cols, axis=1)
target = df_balanced['Sleep Disorder']

X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size=0.2, stratify=target, random_state=42)

model = RandomForestClassifier(n_estimators=300, random_state=42, class_weight="balanced")
model.fit(X_train, y_train)
preds = model.predict(X_test)

print(f"✅ Accuracy: {accuracy_score(y_test,preds):.3f}")
print(classification_report(y_test, preds, target_names=le.classes_))

"""Save and Prepare SHAP Explainer"""

os.makedirs("models", exist_ok=True)
joblib.dump(model, "models/rf_sleep.pkl")
joblib.dump(le, "models/label_encoder.pkl")
joblib.dump(features.columns.tolist(), "models/feature_cols.pkl")

feature_cols = joblib.load("models/feature_cols.pkl")
feature_template = pd.DataFrame(columns=feature_cols)

explainer = shap.TreeExplainer(model)  #XAI
background = X_train.sample(n=min(50,len(X_train)),random_state=42) #calculates each feature deviation from baseline
print("✅ SHAP Ready:", background.shape)

""" SHAP Function"""

def compute_local_shap(explainer_obj, sample_df, top_k=5):
    aligned = sample_df.reindex(columns=feature_cols, fill_value=0)
    X = aligned.values
    shap_vals = explainer_obj.shap_values(X)
    pred_idx = int(model.predict(X)[0])
    class_shap = np.ravel(shap_vals[pred_idx][0])
    sorted_idx = np.argsort(np.abs(class_shap))[::-1][:top_k]
    contributions = [
        f"{feature_cols[i]}** → {'+' if class_shap[i]>0 else ''}{class_shap[i]:.3f}"
        for i in sorted_idx
    ]
    return "\n".join(contributions), shap_vals[pred_idx][0]

"""Medical Chatbot (with PubMed + local knowledge)"""

# Download Phi-3 model
!wget -q https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf -O phi3.gguf

import requests, time, random
from llama_cpp import Llama

# 🔹 Load Phi-3 model (make sure phi3.gguf is already downloaded)
llm = Llama(model_path="phi3.gguf", n_ctx=4096, n_threads=4)

# 🔹 Cache to avoid repeated calls
evidence_cache = {}

# 🔹 Fallback in case online evidence fails
LOCAL_FALLBACK = """\
⚠ Using fallback evidence:

- Sleep apnea involves repeated breathing interruptions during sleep, often linked to obesity or airway blockage.
- Insomnia is commonly related to stress, irregular schedules, or caffeine intake; CBT-I is the recommended first-line therapy.
- Good sleep hygiene includes fixed bedtime, avoiding caffeine after noon, limiting screens before bed, and maintaining a cool, dark room.
"""


def search_pubmed(query, max_results=3):
    """Fetch PubMed article titles safely."""
    try:
        base = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
        params = {"db": "pubmed", "term": query, "retmode": "json", "retmax": max_results}
        resp = requests.get(base, params=params, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        ids = data.get("esearchresult", {}).get("idlist", [])
        if not ids:
            return None

        summaries = []
        for pid in ids:
            s_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi"
            s = requests.get(s_url, params={"db": "pubmed", "id": pid, "retmode": "json"}, timeout=10)
            s.raise_for_status()
            info = s.json()["result"].get(pid, {})
            title = info.get("title", "No Title")
            date = info.get("pubdate", "n.d.")
            summaries.append(f"🧾 [{title}](https://pubmed.ncbi.nlm.nih.gov/{pid}/) ({date})")
        return "\n".join(summaries)
    except Exception as e:
        print("⚠ PubMed error:", e)
        return None


def search_europepmc(query, max_results=3):
    """Fetch EuropePMC results safely."""
    try:
        url = f"https://www.ebi.ac.uk/europepmc/webservices/rest/search"
        params = {"query": query, "format": "json", "pageSize": max_results}
        r = requests.get(url, params=params, timeout=10)
        r.raise_for_status()
        data = r.json()
        results = data.get("resultList", {}).get("result", [])
        if not results:
            return None

        out = []
        for item in results:
            title = item.get("title", "No Title")
            src = item.get("source", "MED")
            pid = item.get("id", "N/A")
            link = f"https://europepmc.org/article/{src}/{pid}"
            year = item.get("pubYear", "n.d.")
            out.append(f"🧾 [{title}]({link}) ({year})")
        return "\n".join(out)
    except Exception as e:
        print("⚠ EuropePMC error:", e)
        return None


def medical_chatbot(user_query, patient_features=None, shap_text=None):
    """Generate structured medical response with live or fallback evidence."""
    # ✅ Try cache first
    if user_query in evidence_cache:
        evidence_text = evidence_cache[user_query]
    else:
        pubmed = search_pubmed(user_query)
        epmc = search_europepmc(user_query)

        if pubmed or epmc:
            evidence_text = f"""
🔎 *PubMed Evidence*
{pubmed or 'No PubMed results.'}

🌍 *EuropePMC Evidence*
{epmc or 'No EuropePMC results.'}
"""
        else:
            evidence_text = LOCAL_FALLBACK

        evidence_cache[user_query] = evidence_text

    # ✅ Build LLM prompt
    prompt = f"""
You are a medically-safe assistant focusing on sleep disorders.
Be evidence-based, clear, and concise.
Never diagnose, only explain patterns and offer general advice.

USER QUESTION:
{user_query}

PATIENT DETAILS:
{patient_features}

MODEL EXPLANATION (SHAP):
{shap_text}

EVIDENCE:
{evidence_text}

RESPONSE FORMAT:
Assessment:
Medical Explanation:
Evidence Summary:
Personalized Sleep Hygiene Plan:
Red-flag Warning (if any):
"""

    try:
        res = llm(prompt, max_tokens=700, temperature=0.2)
        text = res["choices"][0]["text"] if isinstance(res, dict) else str(res)
    except Exception as e:
        text = f"⚠ LLM error: {e}\n\nUsing fallback summary:\n{LOCAL_FALLBACK}"

    return text.strip(), evidence_text

"""Prepare Input Function

"""

def prepare_input_row(user_inputs: dict):
    df_user = pd.DataFrame([user_inputs])

    # Auto-handle Gender if provided as plain text
    if "Gender" in df_user.columns:
        df_user["Gender_Male"] = (df_user["Gender"].astype(str).str.lower() == "male").astype(int)
        df_user.drop("Gender", axis=1, inplace=True)

    # Fill dummy categorical columns if missing
    for col in feature_template.columns:
        if col not in df_user.columns:
            df_user[col] = 0

    # Reindex and ensure numeric
    df_aligned = df_user.reindex(columns=feature_template.columns, fill_value=0)
    df_aligned = df_aligned.apply(pd.to_numeric, errors='coerce').fillna(0)

    # Debug print to check what goes to model
    nonzero = df_aligned.loc[:, (df_aligned != 0).any(axis=0)]
    print("🧩 Nonzero input features:\n", nonzero.T)
    return df_aligned

"""Gradio Interface

"""

import gradio as gr
import numpy as np

def gradio_chat(user_query, age, gender, sleep_hours, stress_level, caffeine, activity=5, bp_sys=120, bp_dia=80):
    try:
        if not user_query.strip():
            return "⚠ Please enter a question."

        # --- Prepare input for model ---
        user_input = {
            "Age": age,
            "Sleep Duration": sleep_hours,
            "Stress Level": stress_level,
            "Caffeine Consumption": caffeine,
            "Physical Activity Level": activity,
            "Systolic": bp_sys,
            "Diastolic": bp_dia,
            "Gender_Male": 1 if gender == "Male" else 0
        }

        inp = prepare_input_row(user_input)
        probs = model.predict_proba(inp)[0]
        pred_idx = np.argmax(probs)
        pred_label = le.inverse_transform([pred_idx])[0]
        confidence = probs[pred_idx]

        # --- Compute SHAP values ---
        shap_text, class_shap = compute_local_shap(explainer, inp, top_k=5)
        shap_dict = {f: float(v) for f, v in zip(feature_cols, class_shap)}

        # --- SHAP refinement heuristic ---
        sleep_dur = shap_dict.get("Sleep Duration", 0)
        stress_val = shap_dict.get("Stress Level", 0)
        bmi_over = shap_dict.get("BMI Category_Obese", 0)
        bmi_overwt = shap_dict.get("BMI Category_Overweight", 0)

        if sleep_dur < -0.03 and stress_val > 0.02:
            refined_label = "Insomnia"
        elif bmi_over > 0.05 or bmi_overwt > 0.05:
            refined_label = "Sleep Apnea"
        else:
            refined_label = pred_label

        # trust SHAP refinement if model confidence < 0.8
        final_label = refined_label if confidence < 0.8 else pred_label

        patient_features = f"""
Age: {age}, Gender: {gender}, Sleep Duration: {sleep_hours}h
Stress Level: {stress_level}/10, Caffeine: {caffeine}mg/day
Activity: {activity}/10, BP: {bp_sys}/{bp_dia} mmHg
"""

        # --- Call medical chatbot (tuple-safe) ---
        reply_data = medical_chatbot(user_query, patient_features, shap_text)
        if isinstance(reply_data, tuple):
            reply, evidence = reply_data
        else:
            reply = str(reply_data)
            evidence = "No external evidence found."

        # --- Color theme ---
        color = "#43a047" if final_label == "Healthy" else "#fb8c00" if final_label == "Insomnia" else "#e53935"
        emoji = "🌿" if final_label == "Healthy" else "🌙" if final_label == "Insomnia" else "💤"

        # --- Return formatted HTML ---
        return f"""
        <div style='background:#f5f9ff;padding:20px;border-radius:15px;font-family:Segoe UI;'>
            <div style='border-left:8px solid {color};padding-left:10px;margin-bottom:10px;'>
            </div>

            <h2 style='color:#1565C0;margin-top:0;'>🧠 <b>Top SHAP Insights</b></h2>
            <div style='background:#FFFFFF;padding:12px 15px;border-radius:12px;
                        font-size:15px;font-family:"Courier New";line-height:1.4;
                        border-left:5px solid #64B5F6;'>
                {shap_text.replace('\n','<br>')}
            </div>


            <h4>📚 AI Medical Guidance</h4>
            <div style='background:#fff;border-left:4px solid #81C784;padding:10px;border-radius:10px;white-space:pre-wrap;word-wrap:break-word;'>
                {reply.replace('\n','<br>')}
            </div>

            <h4>🔗 Evidence Sources</h4>
            <div style='background:#fff;border-left:4px solid #90A4AE;padding:10px;border-radius:10px;max-height:250px;overflow-y:auto;'>
                {evidence.replace('\n','<br>')}
            </div>
        </div>
        """

    except Exception as e:
        import traceback
        traceback.print_exc()
        return f"⚠ Error: {str(e)}"

# ------------------- UI -------------------
with gr.Blocks(theme=gr.themes.Soft(primary_hue="blue")) as demo:
    gr.HTML("""
    <div style='text-align:center; padding:15px;'>
        <h1 style='color:#2B6CB0;'>💤 SleepWell AI</h1>
        <p style='color:gray;'>Your personal AI sleep companion — powered by Explainable AI and medical evidence.</p>
    </div>
    """)

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("### 💬 Ask Your Question")
            q = gr.Textbox(label="Enter your sleep question",
                           placeholder="e.g., Why do I feel tired even after sleeping 8 hours?")

            gr.Markdown("### 🧍 Patient Information")
            age = gr.Number(label="Age", value=30)
            gender = gr.Radio(["Male", "Female"], value="Male", label="Gender")

            gr.Markdown("### 🏃 Lifestyle Factors")
            sleep_hours = gr.Number(label="Sleep Duration (hours)", value=6)
            stress_level = gr.Slider(0, 10, value=5, label="Stress Level (0 = low, 10 = high)")
            caffeine = gr.Number(label="Daily Caffeine (mg)", value=100)
            activity = gr.Slider(1, 10, value=5, label="Physical Activity (1 = low, 10 = high)")

            gr.Markdown("### ❤ Health Info")
            bp_sys = gr.Number(label="Systolic BP (mmHg)", value=125)
            bp_dia = gr.Number(label="Diastolic BP (mmHg)", value=80)

            analyze_btn = gr.Button("🔍 Analyze", variant="primary")

        with gr.Column(scale=2):
            gr.Markdown("### 📊 AI Analysis & Explanation")
            ans = gr.HTML(label="Results", elem_id="result_box")

    analyze_btn.click(
        fn=gradio_chat,
        inputs=[q, age, gender, sleep_hours, stress_level, caffeine, activity, bp_sys, bp_dia],
        outputs=ans
    )

    gr.Markdown("""
    ---
    ⚙ Note: This AI assistant uses a trained Random Forest model and live PubMed evidence retrieval.
    It provides educational insights — not a substitute for professional medical advice.
    """)

demo.launch()

